//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelDeals.Data.DbProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public string CITY { get; set; }
        public int HOTELID { get; set; }
        public string ROOM { get; set; }
        public int PRICE { get; set; }
    }
}
